spring:
  application:
    name: review
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9600/eureka
---
spring:
  profiles: config0
server:
  port: 9510
---
spring:
  profiles: config1
server:
  port: 9511
---
spring:
  profiles: config2
server:
  port: 9512