spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9600/eureka/,http://peer2:9601/eureka/,http://peer3:9603/eureka/

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
server:
  port: 9600
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
server:
  port: 9601
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
server:
  port: 9603