# 公共配置，服务名字和serviceurl,其中serviceurl写入了3个节点的地址
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9600/eureka/,http://peer2:9601/eureka/,http://peer3:9603/eureka/

# 配置三套不同的配置，yml支持用“---”分隔不同的配置
---
# spring.profiles指定配置名字，运行时通过改名字指定选用该套配置
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
server:
  port: 9600
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
server:
  port: 9601
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
server:
  port: 9603