# 共享配置
spring:
  application:
    name: eureka-demo-server
# 注册地址，逗号隔开表示多个服务端存在
eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:9600/eureka/,http://localhost:9601/eureka/,http://localhost:9602/eureka/
# yml 支持通过 --- 方式分隔多套配置
---
spring:
  profiles: peer0
server:
  port: 9600
---
spring:
  profiles: peer1
server:
  port: 9601
---
spring:
  profiles: peer2
server:
  port: 9602